name: Onboarding Request
description: Use this template to file an onboarding request for a new service / tool for the Azure MCP server.
title: "[ONBOARD]"
labels: ["onboarding","needs-triage"]
projects: ["Azure/812"]

body:
  - type: input
    id: library
    attributes:
      label: Service / Tool Name
      description: Name and description of the Azure service or tool you want to onboard.
      placeholder: ex. Azure.Storage.Blobs
    validations:
      required: true
  - type: input
    id: contacts
    attributes:
      label: Contacts
      description: List of contacts who own the Service / Tool being onboarded
      placeholder: ex. Alice Cooper (alcoop), Bob Dylan (bdylan)
    validations:
      required: true
  - type: textarea
    id: scenarios
    attributes:
      label: Intended Agent Scenarios
      description: What customer scenarios are you trying to solve with this service or tool? Please provide a brief description of the scenarios and how they relate to the Azure MCP server.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: May 2025, November 2025, TBD, etc.
        Please provide your desired timeline
      placeholder: TBD
    validations:
      required: true
