jobs:
- job: PublishDev
  displayName: "Publish to dev feed"
  condition: and(succeeded(), ne(variables['Skip.PublishPackage'], 'true'))
  steps:
  - checkout: self

  - download: current
    displayName: Download $(PipelineArtifactName)_packed
    artifact: $(PipelineArtifactName)_packed
    
  - template: /eng/pipelines/templates/steps/npm-release-task.yml
    parameters:
      PathToArtifacts: $(Pipeline.Workspace)/$(PipelineArtifactName)_packed
      Registry: https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-js/npm/registry/
      ${{ if and(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'IndividualCI')) }}:
        Tag: latest
      ${{ else }}:
        Tag: dev
      
# - job: PublishDocsToNightly
#   displayName: "Update Package Versions"
#   condition: and(succeeded(), or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal'))))
#   dependsOn: PublishDev
#   steps:
#   - checkout: self
#   TODO: Add the steps to publish the docs
