parameters:
# required matrix parameters
- name: UsePlatformContainer
  type: boolean
- name: OSName
  type: string
- name: Matrix
  type: object
- name: DependsOn
  type: string
- name: CloudConfig
  type: object

jobs:
- job: Test_${{ parameters.OSName }}
  displayName: "Test"
  dependsOn:
  - ${{ parameters.DependsOn }}
  strategy:
    matrix: $[ ${{ parameters.Matrix }} ]
  pool:
    name: $(Pool)
    ${{ if eq(parameters.OSName, 'macOS') }}:
      vmImage: $(OSVmImage)
    ${{ else }}:
      image: $(OSVmImage)
    os: ${{ parameters.OSName }}
  variables:
    Version: $[ dependencies.Initialize.outputs['Version.Version'] ]
  steps:
  - checkout: self

  - task: UseDotNet@2
    displayName: "Use .NET SDK from global.json"
    retryCountOnTaskFailure: 3
    inputs:
      useGlobalJson: true

  - task: Powershell@2
    displayName: "Run tests"
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/eng/scripts/Test-Code.ps1

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    displayName: "Publish Results"
    inputs:
      testResultsFiles: "$(Build.SourcesDirectory)/.work/testResults/*.trx"
      testRunTitle: "${{ parameters.OSName }}"
      testResultsFormat: "VSTest"
      mergeTestResults: true

  - task: PublishCodeCoverageResults@2
    displayName: Publish Code Coverage Reports
    inputs:
      summaryFileLocation: $(CoverageFile)
